# Generated by Django 3.0.7 on 2020-06-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='room_name',
            field=models.CharField(max_length=20),
        ),
    ]
